### ISSUE TITLE
"7.0.8-0ubuntu0.16.04.2" version raise error "TypeError: Cannot set property 'build' of null"

### ISSUE THREAD

**Issue by KodeKracker** [sindresorhus/semver-truncate#2]
This version `7.0.8-0ubuntu0.16.04.2`  is of PHP installed on my system currently, and I am using a library [gulp-connect-php](https://www.npmjs.com/package/gulp-connect-php) for my PHP work. Actually, this library has a dependency on library [bin-version-check](https://www.npmjs.com/package/bin-version-check) which depends on this library.

**gulp-connect-php** [Line](https://github.com/micahblu/gulp-connect-php/blob/master/index.js#L95) uses **bin-version-check** [Line](https://github.com/sindresorhus/bin-version-check/blob/master/index.js#L16) to check the PHP version and, then **bin-version-check** retrieve system PHP version and use `semverTruncate()`. 

On my system, PHP version is `7.0.8-0ubuntu0.16.04.2`. So, this library raises an error. 

```
/**********/node_modules/semver-truncate/index.js:11
version.build = '';
	              ^

TypeError: Cannot set property 'build' of null
```

TestCase:- `semverTruncate("7.0.8-0ubuntu0.16.04.2", "patch")` to create this error.

**Comment by sindresorhus** [comment]
That's because `7.0.8-0ubuntu0.16.04.2` is not valid semver.

> Numeric identifiers MUST NOT include leading zeroes.
> - http://semver.org/#spec-item-9

**Comment by sindresorhus** [comment]
I've made it a bit looser now though.

**Comment by KodeKracker** [comment]
@sindresorhus thanks.
